### ISSUE TITLE
Nessie in the Friendly Arm Inn talks about Dorn even if he is disabled

### ISSUE THREAD

**Issue by tomasz1986** [Argent77/A7-NoEENPCs#1]
I know that this is probably difficult to fix, as the dialogue would have to be changed in all the different language versions of the game, but still.

Nessie, the lady working in the Friendly Arm Inn, when asked talks about the people present in the Inn. Among them, she mentions Dorn standing in the corner or something like that. This part of the dialogue should be removed when Dorn himself is disabled in the mod.

**Comment by Argent77** [comment]
Thanks. It looks like the Dorn reference is in a separate sentence that can be cut without having to rewrite the remaining content. It should be quite easy to fix.

**Comment by Argent77** [comment]
[Fixed](https://github.com/Argent77/A7-NoEENPCs/commit/db422ee12d94f48d3e5453196cfb72728496f1e0).
