### ISSUE TITLE
Nessie's dialogue references the wrong string in EET

### ISSUE THREAD

**Issue by testlum** [Argent77/A7-NoEENPCs#4]
As per [jmerry's explanation on the G3 forums](https://www.gibberlings3.net/forums/topic/35136-text-errors-and-suggestions/?do=findComment&comment=326635), the conversation with Nessie in the Friendly Arm links to #18576 instead of #218576 in EET like it's supposed to.

![2023-09-01 11_50_14-Baldur's Gate - Enhanced Edition Trilogy - v2 6 6 0](https://github.com/Argent77/A7-NoEENPCs/assets/65993546/1c87912f-fb41-4e95-8139-8efd834fc0db)

**Comment by Argent77** [comment]
Thanks. It's fixed in the `devel` branch (18efcb4c0d37af8cbabfe07b2130976389dcdae2) and will be available in the next release.
